apiVersion: apps/v1
kind: Deployment
metadata:
  name: adaptivehello-deployment
spec:
  selector:
    matchLabels:
      app: adaptivehello
  replicas: 1
  template:
    metadata:
      labels:
        app: adaptivehello
    spec:
      containers:
      - name: adaptivehello
        image: adaptivenetlab/research:hello1.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: adaptivehello-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: adaptivehello
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adaptivehello-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: hello.from.adaptivenetworklab.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adaptivehello-service
                port:
                  number: 80