name: GCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Login to DockerHub
      uses : docker/login-action@v1
      with :
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build & Push
      id : docker_build
      uses : docker/build-push-action@v2
      with :
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/research:hello1.0